"""add note_book note_note note_asset

Revision ID: 0e91df108d7c
Revises: b28d57267979
Create Date: 2026-03-18 19:47:13.866555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e91df108d7c'
down_revision: Union[str, Sequence[str], None] = 'b28d57267979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('note_note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('json_url', sa.String(length=2048), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['note_book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('json_url')
    )
    op.create_index(op.f('ix_note_note_book_id'), 'note_note', ['book_id'], unique=False)
    op.create_table('note_asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('asset_url', sa.String(length=2048), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type IN ('svg', 'png', 'jpg', 'jpeg', 'excalidraw')", name='ck_note_asset_asset_type'),
    sa.ForeignKeyConstraint(['note_id'], ['note_note.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_asset_asset_url'), 'note_asset', ['asset_url'], unique=True)
    op.create_index(op.f('ix_note_asset_note_id'), 'note_asset', ['note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_asset_note_id'), table_name='note_asset')
    op.drop_index(op.f('ix_note_asset_asset_url'), table_name='note_asset')
    op.drop_table('note_asset')
    op.drop_index(op.f('ix_note_note_book_id'), table_name='note_note')
    op.drop_table('note_note')
    op.drop_table('note_book')
    # ### end Alembic commands ###
